connect system/123456;

ALTER SESSION SET CONTAINER = ORCLPDB1;
CREATE TABLESPACE CONTROLE_TBS DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/controletbs01.dbf' SIZE 100M ONLINE;
CREATE TABLESPACE IDX_CONTROLE_TBS DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/idx_controletbs01.dbf' SIZE 100M;
CREATE USER CONTROLE IDENTIFIED BY CONTROLE DEFAULT TABLESPACE CONTROLE_TBS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO CONTROLE;
GRANT RESOURCE TO CONTROLE;
GRANT CREATE VIEW TO CONTROLE;
GRANT CREATE PROCEDURE TO CONTROLE;
GRANT CREATE JOB TO CONTROLE;
GRANT CREATE MATERIALIZED VIEW TO CONTROLE;
ALTER USER CONTROLE DEFAULT ROLE CONNECT, RESOURCE;
ALTER USER CONTROLE QUOTA UNLIMITED ON CONTROLE_TBS;